

## Deployed the app to azure
## http://20.164.53.80:5555/swagger-ui/index.html
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: schoolmanagementsystem
    ports:
      - "3300:3306"
    networks:
      - schoolmanagementsystemnetwork

  springboot:
    image: school-management-system-spring:latest
    container_name: school-management-system-spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/schoolmanagementsystem
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - mysql
    networks:
      - schoolmanagementsystemnetwork

networks:
  schoolmanagementsystemnetwork:
    driver: bridge
