
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: school_management
    ports:
      - "3307:3306"
    networks:
      - schoolmanagementsystemnetwork

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-management-system-spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/school_management
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - mysql
    networks:
      - schoolmanagementsystemnetwork

networks:
  schoolmanagementsystemnetwork:
    driver: bridge
